Download checksum from pivnet and download product from product.solace.com

diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -2,55 +2,96 @@
 
 set -e
 
-LOG="/var/log/in.log"
+source /opt/resource/common.sh
 
-echo "Solace Product Download" >&2
-PAYLOAD=$(mktemp /tmp/resource-check.XXXXXX)
+log "Solace Product Download"
 
-cat > "$PAYLOAD" <&0
+readPayload
 
-username=$(jq -r '.source.username // ""' < $PAYLOAD)
-password=$(jq -r '.source.password // ""' < $PAYLOAD)
-accept=$(jq -r '.source.accept_terms // "false"' < $PAYLOAD)
-filepath=$(jq -r '.source.filepath // ""' < $PAYLOAD)
-targetdir=$1
+export CONFIG_CHECKSUM=$(getPayloadProperty ".version.config_checksum")
+export USERNAME=$(getPayloadProperty ".source.username")
+export PASSWORD=$(getPayloadProperty ".source.password")
+export ACCEPT_TERMS=$(getPayloadProperty ".source.accept_terms")
+export FILEPATH=$(getPayloadProperty ".source.filepath")
+export PIVNET_REFRESH_TOKEN=$(getPayloadProperty ".source.pivnet_token")
+export TARGET_DIRECTORY="$1"
 
-if [ -z $username ]; then
-  echo "Solace Product username must be specified in source block. 'username: <username>'" >&2
+if [ -z $TARGET_DIRECTORY ]; then
+  log "Usage: $0 <target>"
+  exit 1
+fi
+
+if [ -z "$USERNAME" ]; then
+  log "Solace Product username must be specified in source block. 'username: <username>'"
   echo "{}"
   exit 1
 fi
 
-if [ -z $password ]; then
-  echo "Solace Product password must be specified in source block. 'password: <password>'" >&2
+if [ -z "$PASSWORD" ]; then
+  log "Solace Product password must be specified in source block. 'password: <password>'"
   echo "{}"
   exit 1
 fi
 
-if [ -z $filepath ]; then
-  echo "File path must be specified in source block. 'filepath: <path>'" >&2
+if [ ! -z "$PIVNET_REFRESH_TOKEN" ]; then
+  log "Pivnet refresh token provided, discovering latest version from Pivnet"
+  log
+
+  getPivnetRefreshToken
+
+  downloadChecksumFromPivnet
+
+  if [ -z $CHECKSUM_FILE ]; then
+    log "Checksum file could not be downloaded!"
+    exit 1
+  fi
+
+  log "Successfully downloaded checksum from $pubsub_checksum_url"
+  log
+
+  parseChecksum $CHECKSUM_FILE
+  export FILEPATH="/products/$PUBSUB_GA/PCF/Current/$PUBSUB_VERSION/$PUBSUB_FILENAME"
+  
+  log "Discovered filepath $filepath from checksum"
+  log
+fi
+
+if [ -z "$FILEPATH" ]; then
+  log "File path must be specified in source block for Solace Product Download resource or a Pivnet refresh token must be provided. 'filepath: <path>' or 'pivnet_token: <pivnet_token>'"
   echo "{}"
   exit 1
 fi
 
-FLAGS="-u $username -p $password -d $filepath"
+export FLAGS="-u $USERNAME -p $PASSWORD -d $FILEPATH"
 
-echo "Acceptance of terms: $accept" >&2
+log "Acceptance of terms: $ACCEPT"
 
-if [ "$accept" == "true" ]; then
-  FLAGS="$FLAGS -a"
+if [ "$ACCEPT_TERMS" == "true" ]; then
+  export FLAGS="$FLAGS -a"
 else
-  echo "Accepting the Solace License Agreement is required to download products from solace. Please add 'accept_terms: true' to the resource 'source' section." >&2
+  log "Accepting the Solace License Agreement is required to download products from solace. Please add 'accept_terms: true' to the resource 'source' section."
   echo "{}"
   exit 1
 fi
 
-echo "Downloading $filepath, will be placed in $targetdir" >&2
+if [ ! -z "$CHECKSUM_FILE" ]; then
+  FLAGS="$FLAGS -c $CHECKSUM_FILE"
+fi
+
+log "Downloading $FILEPATH, will be placed in $TARGET_DIRECTORY"
 
 /opt/resource/downloadLicensedSolaceProduct.sh $FLAGS >&2
 
-mv *.pdf $targetdir
-mv *.pivotal $targetdir
-ls $targetdir >&2
+if [ "$(ls | grep .pivotal | wc -l)" -eq 0 ]; then
+  log "Could not find enterprise tile at $FILEPATH, is it released?"
+  exit 1
+fi
 
-echo "{\"version\": {\"filepath\":\"$filepath\"}, \"metadata\":[]}"
+mv *.pdf $TARGET_DIRECTORY
+mv *.pivotal $TARGET_DIRECTORY
+ls $TARGET_DIRECTORY >&2
+
+version_id=${PUBSUB_PIVNET_VERSION_ID:-""}
+downloaded_filename="$(basename $FILEPATH)"
+
+echo "{\"version\": {\"config_checksum\":\"$CONFIG_CHECKSUM\",\"pubsub_version_id\":\"$version_id\"}, \"metadata\":[{\"name\":\"filename\",\"value\":\"$downloaded_filename\"}]}"
